In [1]:
import pandas as pd


In [4]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [5]:
obj=Series([4,7,-5,3])

In [6]:
print(obj.values)
print (obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


In [7]:
obj.index=['bob','smith','KR','WS']

In [8]:
print(obj)

bob      4
smith    7
KR      -5
WS       3
dtype: int64


In [9]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)

d    4
b    7
a   -5
c    3
dtype: int64


In [10]:
print(obj2.index)

Index(['d', 'b', 'a', 'c'], dtype='object')


In [11]:
print(obj2.values)

[ 4  7 -5  3]


In [12]:
print(obj2['a'])

-5


In [13]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)


In [14]:
frame = DataFrame(data, columns=['year', 'state', 'pop'])

frame

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [15]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
    index=['one', 'two', 'three', 'four', 'five'])

frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [16]:
matdict=pd.read_json(r'test2.json')

In [17]:
print(matdict.index)

Index(['!! material system', 'data name'], dtype='object')


In [18]:
print(matdict.values[0])

['표준위 심의안 (230210) 이후 working' 'suggestion' 'K-MDS 기등록 어휘 반영'
 'need to check'
 {'eng_definition': 'selected materials system of the data', 'var_name': 'MaterialSystem', 'alias': '', 'data_type': 'string ', 'data_example': ['no system', 'catalyst', 'porous_materials', 'memristive', 'photodetector', 'gas_sensor', 'alkali_ion_battery', 'piezoelectric']}]


In [19]:
print(matdict)

                             working dictionary          !!               **  \
!! material system  표준위 심의안 (230210) 이후 working  suggestion  K-MDS 기등록 어휘 반영   
data name           표준위 심의안 (230210) 이후 working  suggestion  K-MDS 기등록 어휘 반영   

                               ??  \
!! material system  need to check   
data name           need to check   

                                                  metadata vocabulary  
!! material system  {'eng_definition': 'selected materials system ...  
data name           {'eng_definition': 'name of the data set, name...  


In [20]:
print(type(matdict))

<class 'pandas.core.frame.DataFrame'>


In [21]:
print(matdict.values[:])

[['표준위 심의안 (230210) 이후 working' 'suggestion' 'K-MDS 기등록 어휘 반영'
  'need to check'
  {'eng_definition': 'selected materials system of the data', 'var_name': 'MaterialSystem', 'alias': '', 'data_type': 'string ', 'data_example': ['no system', 'catalyst', 'porous_materials', 'memristive', 'photodetector', 'gas_sensor', 'alkali_ion_battery', 'piezoelectric']}]
 ['표준위 심의안 (230210) 이후 working' 'suggestion' 'K-MDS 기등록 어휘 반영'
  'need to check'
  {'eng_definition': 'name of the data set, named by data provider', 'var_name': 'DataName', 'data_type': 'string', 'data_example': 'Zinc coated Fe-6Mn-3Al steel plate; Ti/Al dissimilar welded joint; Fe/C catalyst; Gd doped MOF 370; LLZO (Li7La3Zr2O12) Solid Electrolyte'}]]


# NumPy


In [22]:
import numpy as np
data=np.array([1,2,3,4,5,6,7])

In [12]:
sliced_data=data[4:]
print(sliced_data)

[5 6 7]


In [14]:
new_data=np.append(data,[8,9,10])
print(new_data)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
empty_array=np.empty((3,3))
print(empty_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
zeros_array=np.ones_like(data)
print(zeros_array)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [42]:
added=np.add(data, zeros_array)

In [43]:
print(added)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [51]:
arr=np.array([True,False, True, False])
result=np.any(arr)
print(result)

True


In [53]:
result=np.all(arr)
print(result)

False


In [55]:
print(result,True)

False True


In [56]:
arr=np.array([1,2,3,4,5])
indices=np.where(arr>3)
print(indices)

(array([3, 4], dtype=int64),)


In [57]:
arr_2d=np.arange(12).reshape(3,4)
arr_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [58]:
arr_2d=np.arange(12).reshape(3,4)
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
print(arr_2d[1,2])

6


In [60]:
print(arr_2d[1,:])

[4 5 6 7]


In [61]:
print(arr_2d[1])

[4 5 6 7]


In [62]:
print(arr_2d[2])

[ 8  9 10 11]


In [73]:
print(arr_2d[1:3,-2:])

[[ 6  7]
 [10 11]]


In [66]:
print(arr_2d[::2,1::2])

[[ 1  3]
 [ 9 11]]


In [74]:
print(np.sum(arr_2d))

66


In [75]:
print(np.sum(arr_2d, axis=0))

[12 15 18 21]


In [76]:
print(np.sum(arr_2d, axis=1))

[ 6 22 38]


In [82]:
print(np.hstack((arr_2d, np.array([[10],[26],[42]]))))

[[ 0  1  2  3 10]
 [ 4  5  6  7 26]
 [ 8  9 10 11 42]]


In [85]:
print(np.vstack((arr_2d, np.array([[22,26,44,30]]))))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [22 26 44 30]]


# Padas

In [23]:
from pandas import Series, DataFrame 
import pandas as pd
import numpy as np

In [24]:
obj=Series([4,7,-5,3])

In [94]:
print(obj.values)

[ 4  7 -5  3]


In [25]:
print(obj.values)
print(obj.index)

[ 4  7 -5  3]
RangeIndex(start=0, stop=4, step=1)


### Study about 'ydata-profiling' package for data analysis

conda install -c panda


In [26]:
obj.index=['bob','steve','Jeff','Ryan']
print(obj)

bob      4
steve    7
Jeff    -5
Ryan     3
dtype: int64


In [27]:
obj2=Series([4,7,-5,3], index=['d','b','c','a'])
print(obj2.values)
print(obj2.index)

[ 4  7 -5  3]
Index(['d', 'b', 'c', 'a'], dtype='object')


In [28]:
print(obj2['d'])
print(obj2['a'])

4
3


In [29]:
print(obj2[['c','a','d']])

c   -5
a    3
d    4
dtype: int64


In [108]:
print(obj2[:'c'])

d    4
b    7
c   -5
dtype: int64


In [110]:
print(obj2['b':'c'])

b    7
c   -5
dtype: int64


In [32]:
print(obj2[obj2>0])
print()
print(obj2*2)
print()
print(np.exp(obj2))

d    4
b    7
a    3
dtype: int64

d     8
b    14
c   -10
a     6
dtype: int64

d      54.598150
b    1096.633158
c       0.006738
a      20.085537
dtype: float64


In [125]:
print('b' in obj2)

True


In [33]:
print('e' in obj2)

False
